stages:
  process:
    cmd: python create_csv_with_dvc.py
    deps:
    - player_stats.csv
    - create_csv_with_dvc.py
    outs:
    - dvc_players_stats.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - dvc_players_stats.csv
    outs:
    - feature_importance.png
    metrics:
    - metrics.json:
        cache: false
